# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "training_step/reconstructed_quantizing_loss"

hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: "mnist-softvq-vae-multi-experience"

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 1

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    params:
      model.optimizer.lr: interval(0.0001, 0.1)
      model.softvq_vae.softvq.temperature: interval(0.1, 10.0)
      model.softvq_vae.vae.latent_size: choice(8, 16, 32, 64)
      model.softvq_vae.softvq.num_quantizing: choice(8, 16, 32, 64, 128)
