_target_: src.models.mnist_vae_module.MNISTLitVAEModule

r_loss_scaler: 10000
kl_div_loss_scaler: 1.0
log_image_row_col: [8, 8]
log_latent_space_sample_num: 1024

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.dense_image_vae.DenseImageVAE
  input_size: 784
  encoder_lin1_size: 256
  encoder_lin2_size: 64
  latent_size: 16
  decoder_lin1_size: 64
  decoder_lin2_size: 256
